### ISSUE TITLE
Platform issue

### ISSUE THREAD

**Issue by pedrosouza9966** [MrKev312/JustDanceEditor#25]
There’s a little issue when it tried to get the platform’s name…

Example: conversation_nx\cache\itf_cooked\nx\world\maps\conversation
It recognizes the platform as `conversation\cache\itf_cooked`, but not `nx`.

While this is not fixed, i need to rename my bundle folders to `conversation_nx\cache\itf_cooked\conversation_nx\cache\itf_cooked\conversation_nx\world\maps\conversation\` to make it work.

**Comment by MrKev312** [comment]
Which version of the tool are you using?

**Comment by pedrosouza9966** [comment]
im using the latest one on the releases tab, i tried compile it myself but i always get an error because of the TexWrapTool (probably its bc i dont have visual studio installed on my pc)

**Comment by pedrosouza9966** [comment]
Update: I managed to compile the JustDanceEditor, it’s getting the platform perfectly and its converting the audio and webm, the problem is that i still can’t use a `cover.png` for a custom cover, or else it’ll give me an error saying that it couldn’t “encode” the image.

**Comment by MrKev312** [comment]
I'm unable to replicate the cover.png error, could you tell me where you've placed the image and dm me the cover.png on Discord (mrkev312)?

**Comment by MrKev312** [comment]
Platform error is solved in a later commit, the cover.png is solved as it was in the wrong location:
``\world\maps\{mapname}\menuart\textures`` instead of ``\world\maps\{mapname}\menuart``
